CREATE OR REPLACE PROCEDURE PROCESAR_PO (
    IN P_LIBRERIA VARCHAR(10), -- Ejemplo: 'RI11DB'
    IN P_NUMERO VARCHAR(2),   -- Ejemplo: '12'
    IN P_ASN VARCHAR(50)      -- Ejemplo: 'ASN1001'
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    DECLARE V_TABLA_INI VARCHAR(30);
    DECLARE V_TABLA_FIN VARCHAR(30);
    DECLARE V_STMT VARCHAR(6000);

    -- 1. Construir nombres de tablas dinámicas
    SET V_TABLA_INI = 'INV_INICIAL' || P_NUMERO;
    SET V_TABLA_FIN = 'INV_FINAL' || P_NUMERO;

    -- 2. Crear INV_INICIAL si no existe en la librería indicada
    IF NOT EXISTS (SELECT * FROM QSYS2.TABLES WHERE TABLE_SCHEMA = UPPER(P_LIBRERIA) AND TABLE_NAME = UPPER(V_TABLA_INI)) THEN
        SET V_STMT = 'CREATE TABLE ' || P_LIBRERIA || '.' || V_TABLA_INI || ' ('
            || 'INVENTARIO VARCHAR(255), STATUSRI VARCHAR(255), U48RE VARCHAR(255), '
            || 'SKU VARCHAR(255), POÑRE VARCHAR(255), STÑRE VARCHAR(255), '
            || 'DATERE VARCHAR(255), ASN VARCHAR(255), UDF3 VARCHAR(255), LN4RE VARCHAR(255))';
        EXECUTE IMMEDIATE V_STMT;
    END IF;

    -- 3. Crear INV_FINAL si no existe en la librería indicada
    IF NOT EXISTS (SELECT * FROM QSYS2.TABLES WHERE TABLE_SCHEMA = UPPER(P_LIBRERIA) AND TABLE_NAME = UPPER(V_TABLA_FIN)) THEN
        SET V_STMT = 'CREATE TABLE ' || P_LIBRERIA || '.' || V_TABLA_FIN || ' ('
            || 'INVENTARIO VARCHAR(255), STATUSRI VARCHAR(255), U48RE VARCHAR(255), '
            || 'SKU VARCHAR(255), POÑRE VARCHAR(255), STÑRE VARCHAR(255), '
            || 'DATERE VARCHAR(255), ASN VARCHAR(255), UDF3 VARCHAR(255), LN4RE VARCHAR(255))';
        EXECUTE IMMEDIATE V_STMT;
    END IF;

    -- 4. INSERT en INV_INICIAL (Origen dinámico de P_LIBRERIA)
    SET V_STMT = 'INSERT INTO ' || P_LIBRERIA || '.' || V_TABLA_INI 
        || ' SELECT (SELECT U27KA FROM ' || P_LIBRERIA || '.KAOHP A WHERE A.SKUKA = SUBSTRING(SKURE, 2, 6) AND STÑKA = STÑRE), '
        || ' STATUSRI, U48RE, SUBSTRING(SKURE, 2, 6), POÑRE, STÑRE, DATERE, ASN, UDF3, LN4RE '
        || ' FROM ' || P_LIBRERIA || '.KRWSPWASIN WHERE ASN = ?';
    PREPARE S1 FROM V_STMT;
    EXECUTE S1 USING P_ASN;

    -- 5. INSERT en INV_FINAL (Origen dinámico de P_LIBRERIA)
    SET V_STMT = 'INSERT INTO ' || P_LIBRERIA || '.' || V_TABLA_FIN 
        || ' SELECT (SELECT U27KA FROM ' || P_LIBRERIA || '.KAOHP A WHERE A.SKUKA = SUBSTRING(SKURE, 2, 6) AND STÑKA = STÑRE), '
        || ' STATUSRI, U48RE, SUBSTRING(SKURE, 2, 6), POÑRE, STÑRE, DATERE, ASN, UDF3, LN4RE '
        || ' FROM ' || P_LIBRERIA || '.KRWSPWASIN WHERE ASN = ?';
    PREPARE S2 FROM V_STMT;
    EXECUTE S2 USING P_ASN;

    -- 6. Actualizar STATUSRI en KRWSPWASIN (Tabla Maestra dinámica)
    SET V_STMT = 'UPDATE ' || P_LIBRERIA || '.KRWSPWASIN SET STATUSRI = ''O'' WHERE ASN <> ?';
    PREPARE S3 FROM V_STMT;
    EXECUTE S3 USING P_ASN;

    SET V_STMT = 'UPDATE ' || P_LIBRERIA || '.KRWSPWASIN SET STATUSRI = ''P'' WHERE ASN = ?';
    PREPARE S4 FROM V_STMT;
    EXECUTE S4 USING P_ASN;
END











CREATE OR REPLACE PROCEDURE ELOPEZ.PROCESAR_ORDENES (
    IN P_LIBRERIA VARCHAR(10), 
    IN P_NUMORDEN VARCHAR(20)
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    DECLARE V_STMT VARCHAR(8000);
    DECLARE V_ORDEN_TRIM VARCHAR(20);

    SET V_ORDEN_TRIM = TRIM(P_NUMORDEN);

    -- 1. ACTUALIZACIONES DIRECTAS DE STATUSRI
    -- Primero: Ponemos 'O' a todos los registros que NO son nuestra orden
    SET V_STMT = 'UPDATE ' || P_LIBRERIA || '.KTCHPWASIN SET STATUSRI = ''O'' WHERE NUMORDEN <> ?';
    PREPARE U1 FROM V_STMT;
    EXECUTE U1 USING V_ORDEN_TRIM;

    -- Segundo: Ponemos 'P' al registro que coincide con nuestra orden
    SET V_STMT = 'UPDATE ' || P_LIBRERIA || '.KTCHPWASIN SET STATUSRI = ''P'' WHERE NUMORDEN = ?';
    PREPARE U2 FROM V_STMT;
    EXECUTE U2 USING V_ORDEN_TRIM;


    -- 2. CREACIÓN DINÁMICA DE TABLAS DE INVENTARIO (Si no existen)
    IF NOT EXISTS (
        SELECT 1 FROM QSYS2.SYSTABLES 
        WHERE TABLE_SCHEMA = UPPER(P_LIBRERIA) AND TABLE_NAME = 'INVENTARIO_INICIAL'
    ) THEN
        SET V_STMT = 'CREATE TABLE ' || P_LIBRERIA || '.INVENTARIO_INICIAL ('
            || 'ORIGEN CHAR(20), SKU CHAR(20), INV_ORIGEN DECIMAL(15, 2), '
            || 'DESTINO CHAR(20), O43TD CHAR(20), INV_DESTINO DECIMAL(15, 2), '
            || 'STATUSRI CHAR(20), DATERE CHAR(20), UNIDADES DECIMAL(15, 2), NUMORDEN CHAR(20))';
        EXECUTE IMMEDIATE V_STMT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM QSYS2.SYSTABLES 
        WHERE TABLE_SCHEMA = UPPER(P_LIBRERIA) AND TABLE_NAME = 'INVENTARIO_FINAL'
    ) THEN
        SET V_STMT = 'CREATE TABLE ' || P_LIBRERIA || '.INVENTARIO_FINAL ('
            || 'ORIGEN CHAR(20), SKU CHAR(20), INV_ORIGEN DECIMAL(15, 2), '
            || 'DESTINO CHAR(20), O43TD CHAR(20), INV_DESTINO DECIMAL(15, 2), '
            || 'STATUSRI CHAR(20), DATERE CHAR(20), UNIDADES DECIMAL(15, 2), NUMORDEN CHAR(20))';
        EXECUTE IMMEDIATE V_STMT;
    END IF;


    -- 3. INSERCIÓN DINÁMICA: INVENTARIO_INICIAL
    SET V_STMT = 'INSERT INTO ' || P_LIBRERIA || '.INVENTARIO_INICIAL '
        || 'SELECT DISTINCT K.SFTTD, SUBSTRING(K.SKUTD, 2, 6), '
        || '(SELECT U27KA FROM ' || P_LIBRERIA || '.KAOHP B WHERE B.SKUKA = SUBSTRING(K.SKUTD, 2, 6) AND B.STÑKA = K.SFTTD), '
        || 'K.STTTD, K.O43TD, '
        || '(SELECT U27KA FROM ' || P_LIBRERIA || '.KAOHP B WHERE B.SKUKA = SUBSTRING(K.SKUTD, 2, 6) AND B.STÑKA = K.STTTD), '
        || 'K.STATUSRI, CHAR(K.DATERE), K.U71TD, K.NUMORDEN '
        || 'FROM ' || P_LIBRERIA || '.KTCHPWASIN K '
        || 'WHERE K.NUMORDEN = ? '
        || 'AND NOT EXISTS (SELECT 1 FROM ' || P_LIBRERIA || '.INVENTARIO_INICIAL I '
        || 'WHERE I.NUMORDEN = K.NUMORDEN AND I.DATERE = CHAR(K.DATERE))';

    PREPARE S1 FROM V_STMT;
    EXECUTE S1 USING V_ORDEN_TRIM;


    -- 4. INSERCIÓN DINÁMICA: INVENTARIO_FINAL
    SET V_STMT = 'INSERT INTO ' || P_LIBRERIA || '.INVENTARIO_FINAL '
        || 'SELECT DISTINCT K.SFTTD, SUBSTRING(K.SKUTD, 2, 6), '
        || '(SELECT U27KA FROM ' || P_LIBRERIA || '.KAOHP B WHERE B.SKUKA = SUBSTRING(K.SKUTD, 2, 6) AND B.STÑKA = K.SFTTD), '
        || 'K.STTTD, K.O43TD, '
        || '(SELECT U27KA FROM ' || P_LIBRERIA || '.KAOHP B WHERE B.SKUKA = SUBSTRING(K.SKUTD, 2, 6) AND B.STÑKA = K.STTTD), '
        || 'K.STATUSRI, CHAR(K.DATERE), K.U71TD, K.NUMORDEN '
        || 'FROM ' || P_LIBRERIA || '.KTCHPWINRC K '
        || 'WHERE K.NUMORDEN = ? '
        || 'AND NOT EXISTS (SELECT 1 FROM ' || P_LIBRERIA || '.INVENTARIO_FINAL I '
        || 'WHERE I.NUMORDEN = K.NUMORDEN AND I.DATERE = CHAR(K.DATERE))';

    PREPARE S2 FROM V_STMT;
    EXECUTE S2 USING V_ORDEN_TRIM;

END





CREATE OR REPLACE PROCEDURE ELOPEZ.SP_PROCESO_COMPLETO_ORDENES (
    IN P_LIBRERIA VARCHAR(10)
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    DECLARE V_FECHA_ACTUAL CHAR(8);
    DECLARE V_ETAPA VARCHAR(100) DEFAULT 'inicio';
    DECLARE V_MSG_ERROR VARCHAR(200);
    DECLARE V_STMT VARCHAR(5000);
    
    -- Manejador de Errores SQL  
    -- LLAMAR EL PROCEDIMIENTO    ELOPEZ.PEGASO('RI12DB')
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1 V_MSG_ERROR = MESSAGE_TEXT;
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = V_MSG_ERROR;
    END;

    -- 1. Obtener fecha actual YYYYMMDD (Ej: 20260106)
    SET V_ETAPA = 'Obteniendo fecha';
    SET V_FECHA_ACTUAL = CONCAT(CONCAT(SUBSTR(CHAR(CURRENT DATE, ISO), 1, 4), 
                                      SUBSTR(CHAR(CURRENT DATE, ISO), 6, 2)), 
                                      SUBSTR(CHAR(CURRENT DATE, ISO), 9, 2));

    -- 2. Ejecutar PO_PEGASO
    SET V_ETAPA = 'Llamando PO_PEGASO';
    CALL ELOPEZ.PO_PEGASO();

    -- 3. PROCESO DE BITÁCORA (Insert masivo dinámico)
    SET V_ETAPA = 'Procesando Bitácora';
    SET V_STMT = CONCAT('INSERT INTO ', CONCAT(TRIM(P_LIBRERIA), 
                 '.BITAC_INFO (IDBASEDATOS, IDTABLA, TIPOPROCESO, FECHAHORA, PKREGISTRO) '
                 'SELECT DISTINCT 50114, 52241, ''I'', CURRENT TIMESTAMP, DOCNUMBER '
                 'FROM ', CONCAT(TRIM(P_LIBRERIA), '.RPLORDEN WHERE DOCNUMBER > 0 AND CREATEDATE = ?')));
    
    PREPARE B1 FROM V_STMT;
    EXECUTE B1 USING V_FECHA_ACTUAL;

    -- 4. UPDATE PMSTP (TIPO_VENDO = I)
    SET V_ETAPA = 'Update PMSTP (I)';
    SET V_STMT = CONCAT('UPDATE ', CONCAT(TRIM(P_LIBRERIA), 
                 '.PMSTP SET C69PM = ''R'', EFRPM = ''U22-559'' '
                 'WHERE POÑPM IN (SELECT DISTINCT DOCNUMBER FROM ', CONCAT(TRIM(P_LIBRERIA), 
                 '.RPLORDEN WHERE DOCNUMBER > 0 AND CREATEDATE = ? AND TIPO_VENDO = ''I'')')));
    PREPARE U1 FROM V_STMT;
    EXECUTE U1 USING V_FECHA_ACTUAL;

    -- 5. UPDATE PMSTP (TIPO_VENDO = L)
    SET V_ETAPA = 'Update PMSTP (L)';
    SET V_STMT = CONCAT('UPDATE ', CONCAT(TRIM(P_LIBRERIA), 
                 '.PMSTP SET C69PM = ''R'' '
                 'WHERE POÑPM IN (SELECT DISTINCT DOCNUMBER FROM ', CONCAT(TRIM(P_LIBRERIA), 
                 '.RPLORDEN WHERE DOCNUMBER > 0 AND CREATEDATE = ? AND TIPO_VENDO = ''L'')')));
    PREPARE U2 FROM V_STMT;
    EXECUTE U2 USING V_FECHA_ACTUAL;

    -- 6. UPDATE PDTLP
    SET V_ETAPA = 'Update PDTLP';
    SET V_STMT = CONCAT('UPDATE ', CONCAT(TRIM(P_LIBRERIA), 
                 '.PDTLP SET C69PD = ''R'' '
                 'WHERE POÑPD IN (SELECT DISTINCT DOCNUMBER FROM ', CONCAT(TRIM(P_LIBRERIA), 
                 '.RPLORDEN WHERE DOCNUMBER > 0 AND CREATEDATE = ?)' )));
    PREPARE U3 FROM V_STMT;
    EXECUTE U3 USING V_FECHA_ACTUAL;

    -- 7. UPDATE PTYPP
    SET V_ETAPA = 'Update PTYPP';
    SET V_STMT = CONCAT('UPDATE ', CONCAT(TRIM(P_LIBRERIA), 
                 '.PTYPP SET C69PS = ''R'' '
                 'WHERE POÑPS IN (SELECT DISTINCT DOCNUMBER FROM ', CONCAT(TRIM(P_LIBRERIA), 
                 '.RPLORDEN WHERE DOCNUMBER > 0 AND CREATEDATE = ?)' )));
    PREPARE U4 FROM V_STMT;
    EXECUTE U4 USING V_FECHA_ACTUAL;

    -- 8. UPDATE SUMMER (Tablas fijas)
    SET V_ETAPA = 'Update SUMMER.POMASTER';
    SET V_STMT = CONCAT('UPDATE SUMMER.POMASTER SET STATUS = ''O'' WHERE MASTERPONUMBER IN '
                 '(SELECT MASTERPONUMBER FROM SUMMER.POSINGLE WHERE PONUMBER IN '
                 '(SELECT DOCNUMBER FROM ', CONCAT(TRIM(P_LIBRERIA), 
                 '.RPLORDEN WHERE DOCNUMBER > 0 AND CREATEDATE = ?)))');
    PREPARE U5 FROM V_STMT;
    EXECUTE U5 USING V_FECHA_ACTUAL;

    SET V_ETAPA = 'Update SUMMER.POSINGLE';
    SET V_STMT = CONCAT('UPDATE SUMMER.POSINGLE SET STATUS = ''O'' WHERE MASTERPONUMBER IN '
                 '(SELECT MASTERPONUMBER FROM SUMMER.POSINGLE WHERE PONUMBER IN '
                 '(SELECT DOCNUMBER FROM ', CONCAT(TRIM(P_LIBRERIA), 
                 '.RPLORDEN WHERE DOCNUMBER > 0 AND CREATEDATE = ?)))');
    PREPARE U6 FROM V_STMT;
    EXECUTE U6 USING V_FECHA_ACTUAL;

END;



CALL PGM(RIUNICOM63/PEGITRXCL) PARM('12' 'WASWMS' '01' ' ')


INSERT INTO RI12DB.RPLTRANSFE
(COMPANYID, COUNTRYID, FORMATID, REFERENCED, AUTOTRF, DOCUMENTNU, CREATEDATE, TRANSFERDA, FECHABY, DETIENDA, PARATIENDA, LINENUMBER, UPC, DBANME, "USERID", JDAORDQTY, WRITTENBY, ONHANDTDA, ONHANDCDD, PENDINGRRI, PROCFLAG)
VALUES('02', '02', '500', '20250614-099-000001     ', 'Y', '0     ', '20250614', '20250617', '20250614', '99 ', '575', '1  ', '469141900011      ', 'RI12DB    ', 'RI12BLY        ', '4     ', 'PEGASO         ', '4              ', '501            ', '  ', ' ');



Guatemala/SmokeTest

Guatemala/Funcionales + Integrales


12653253250011
2238588


013803328





CHGDTAARA DTAARA(RI11DB/DTAARAWIN (13 6)) VALUE('000001')  ---HORA DE CIERRE DEL PROGRAMA 
CHGDTAARA DTAARA(RI11DB/DTAARAWIN (13 6)) VALUE('010000') 
CHGDTAARA DTAARA(RI11DB/DTAARAWIN (19 4)) VALUE('0005') --- TIEMPO QUE TARDA EN EJECUTAR
CHGDTAARA DTAARA(RI11DB/DTAARAWIN (12 1)) VALUE('N')    --- Bandera de bloqueo S BLOQUEADO N No bloqueado
DSPDTAARA DTAARA(RI11DB/DTAARAWIN)   --ver DTAARA







